services:
  - type: web
    name: authnexus
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT --chdir backend run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: authnexus-db
          property: connectionString

databases:
  - name: authnexus-db
    plan: free
    databaseName: authnexus
    user: authnexus_user
